# TIME SPLITTING
# The time window to look at, and how to divide the window into
# train/test splits
temporal_config:
    beginning_of_time: '2000-01-01' # earliest date included in features
    modeling_start_time: '2017-04-01' # earliest date in any model
    modeling_end_time: '2017-09-01' # all dates in any model are < this date
    update_window: '3month' # how frequently to retrain models
    train_label_windows: ['1d']
    test_label_windows: ['3months'] # how much time covered by labels
    train_durations: ['6y'] # length of time included in a model
    test_durations: ['1d'] # length of period to sample from in test set
    train_example_frequency: '1d'
    test_example_frequency: '1d' # how frequently to sample in the test set
    user_metadata:
        label_definition: 'any_serious_violation'

# LABEL GENERATION
# Information needed to generate labels
#
# An events table is expected, with the columns:
#   entity_id - an identifier for which the labels are applied to
#   outcome_date - The date at which some outcome was known
#   outcome - A boolean outcome
# These are used to generate appropriate labels for each train/test split
events_table: 'staging.mh_events'

# FEATURE GROUPING
# define how to group features and generate combinations
# feature_group_definition allows you to create groups/subset of your features
# by different criteria.
# for instance, 'tables' allows you to send a list of collate feature tables
# 'prefix' allows you to specify a list of feature name prefixes
feature_group_definition:
    tables:
        - 'permit_entity_id'
        - 'time_entity_id'
        - 'building_permits_entity_id'
        - 'expired_building_permits_entity_id'
        - 'acs_entity_id'
        - 'days_since_entity_id'
        - 'citations_entity_id'
        - 'inspection_cases_entity_id'
        - 'violations_entity_id'
        - 'all_violations_entity_id'
        - 'violation_cats_entity_id'
        - 'geo_mh_inspections_entity_id'
#        - 'geo_all_violations_entity_id'
        - 'case_length_entity_id'
        - 'violation_length_entity_id'
        - 'delinquent_mh_entity_id'
        - 'mh_foreclosures_entity_id'
        - 'geo_foreclosures_entity_id'
        - 'mh_sale_dates_entity_id'
        - 'house_prices_entity_id'

# strategies for generating combinations of groups
# available: all, leave-one-out, leave-one-in
feature_group_strategies: ['all']

model_group_keys:
    - 'train_duration'
    - 'label_window'
    - 'example_frequency'
    - 'label_definition'

# GRID CONFIGURATION
# The classifier/hyperparameter combinations that should be trained
#
# Each top-level key should be a class name, importable from triage. sklearn is
# available, and if you have another classifier package you would like available,
# contribute it to requirements.txt
#
# Each lower-level key is a hyperparameter name for the given classifier, and
# each value is a list of potential values. All possible combinations of
# classifiers and hyperparameters are trained.
grid_config:
    'sklearn.ensemble.RandomForestClassifier':
        max_features: ['sqrt', 'log2']
        criterion: ['gini', 'entropy']
        n_estimators: [5000]
        min_samples_split: [20, 50]
        max_depth: [10, 50]
        n_jobs: [20]
    'sklearn.ensemble.ExtraTreesClassifier':
        max_features: ['sqrt', 'log2']
        criterion: ['gini', 'entropy']
        n_estimators: [5000]
        min_samples_split: [20, 50]
        max_depth: [10, 50]
        n_jobs: [20]
    'sklearn.linear_model.LogisticRegression':
        penalty: ['l1', 'l2']
        C: [0.001, 0.01, 0.1, 1]
#    'xgboost.sklearn.XGBClassifier':
#        n_estimators: [1000, 5000, 10000]
#        learning_rate: [0.02, 0.05, 0.1, .2]
#        max_depth: [5, 10, 20, 50, 100]

# MODEL SCORING
# How metrics for each model are made and stored
#
# Each entry needs a list of one of the metrics defined in
# triage.scoring.ModelScorer.available_metrics (contributions welcome!)
# Depending on the metric, either thresholds or parameters
#
# Parameters specify any hyperparameters needed. For most metrics,
# which are simply wrappers of sklearn functions, these
# are passed directly to sklearn.
#
# Thresholds are more specific: The list is subset and only the
# top percentile or top n entities are labeled as positive.
scoring:
    metric_groups:
        -
            metrics: ['precision@', 'recall@', 'fpr@']
            thresholds:
                percentiles: [1.0, 2.0, 5.0, 10.0, 25.0]
                top_n: [25, 75, 150, 300, 500, 1000, 1500]
